/*
variable file for AWS EFS module
*/
variable "creation_token" {
    description = "A unique name (a maximum of 64 characters) that ensures the idempotent creation of the file system. This is automatically generated by Terraform and should not be set by users."
    type        = string
    default     = "kubernetes-efs"
}

/*
variable "efs_tags" {
    description = "A map of tags to assign to the resource. If configured with a provider default_tags configuration block present, tags with matching keys will overwrite those defined at the provider-level."
    type        = map(string)
    default     = {
        Name = "kubernetes-efs"
    }
  
}*/

variable "vpc_id_instance" {
    description = "The VPC ID where the security group will be created."
    type        = string
}

variable "subnet_id_instance" {
    description = "The Subnet ID where the EFS mount target will be created."
    type        = string
}

variable "instance_security_group_id" {
    description = "The security group ID of the EC2 instance that needs access to the EFS file system."
    type        = string
  
}
